version: '2'

# Scenario with docker jenkins, smtp server, artifactory, sonarqube.

services:

   jenkins:
    build:
      context: .
      dockerfile: jenkins.Dockerfile
    image: allioli/jenkins:latest
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - smtp
      - artifactory
      - sonarqube

   smtp:
    image: namshi/smtp:latest
   artifactory:
    image: mattgruter/artifactory:latest
    ports:
      - '8081:8080'
    volumes:
      - artifactory_data:/artifactory/data 
      - artifactory_logs:/artifactory/logs 
      - artifactory_backup:/artifactory/backup

   sonarqube:
     image: sonarqube:lts
     ports:
        - "9000:9000"
        - "9092:9092"
     environment:
        SONARQUBE_JDBC_USERNAME: sonar
        SONARQUBE_JDBC_PASSWORD: sonarpasswd
        SONARQUBE_JDBC_URL: "jdbc:postgresql://postgres:5432/sonar"
     depends_on:
        - postgres

   postgres:
      image: postgres:9.6
      environment:
         POSTGRES_USER: sonar
         POSTGRES_PASSWORD: sonarpasswd
      volumes:
         - postgres_data:/var/lib/postgresql/data

volumes:
  jenkins_home:
  artifactory_data:
  artifactory_logs:
  artifactory_backup:
  postgres_data:


